version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./csv:/var/www/html/csv
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
